# Generated by Django 5.0.3 on 2024-04-02 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('energy', models.IntegerField()),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fibre', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_eating', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food', models.ManyToManyField(to='food.food')),
            ],
        ),
        migrations.CreateModel(
            name='Macroelements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phosphor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('magnesium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
        ),
        migrations.CreateModel(
            name='Microelements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluorite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('iodine', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chromium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('copper', models.DecimalField(decimal_places=2, max_digits=6)),
                ('zink', models.DecimalField(decimal_places=2, max_digits=6)),
                ('iron', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
        ),
        migrations.CreateModel(
            name='Vitamins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.DecimalField(decimal_places=2, max_digits=6)),
                ('c', models.DecimalField(decimal_places=2, max_digits=6)),
                ('d', models.DecimalField(decimal_places=2, max_digits=6)),
                ('e', models.DecimalField(decimal_places=2, max_digits=6)),
                ('k', models.DecimalField(decimal_places=2, max_digits=6)),
                ('b1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('b2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('b3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('b5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('b6', models.DecimalField(decimal_places=2, max_digits=6)),
                ('b7', models.DecimalField(decimal_places=2, max_digits=6)),
                ('b9', models.DecimalField(decimal_places=2, max_digits=6)),
                ('b12', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
        ),
    ]
