# Generated by Django 5.0.3 on 2024-07-24 00:33
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
